# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('from_email', models.CharField(max_length=512)),
                ('to', models.CharField(max_length=2024)),
                ('subject', models.CharField(max_length=2024)),
                ('is_multipart', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
